### ISSUE TITLE
delete none standard atrribute when formatting

### ISSUE THREAD

**Issue by ghost** [AnWeber/vscode-tidyhtml#10]
delete none standard atrribute when formatting, like @click=""

**Comment by AnWeber** [comment]
tidy-html5 does not support @... attributes. Please feel free, to create an issue in [tidy-html5 repo](https://github.com/htacg/tidy-html5/issues)

**Comment by AnWeber** [comment]
maybe this issue report is helpful:
https://github.com/htacg/tidy-html5/issues/505
