### ISSUE TITLE
Plugin ignores indent-spaces setting

### ISSUE THREAD

**Issue by BendingBender** [AnWeber/vscode-tidyhtml#11]
Hi! Thank you for the great plugin.

I have a problem with one of the options for HTML Tidy. It seems to ignore (or not to pass through) the [`indent-spaces`](http://api.html-tidy.org/tidy/quickref_5.2.0.html#indent-spaces) option. 

Here is the relevant entry from my config file:
```json
"tidyHtml.optionsTidy": {
    "indent-spaces": 4,
    "wrap": 200
}
```

Is it possible for this plugin to use VS Code's `editor.tabsize` setting so that it isn't necessary to pass this option any more?

**Comment by AnWeber** [comment]
Hi,

sorry, but I could not reproduce the issue with this html
```
<html>
  <div></div>
</html>
```

Maybe your html block contains not valid extension like angularjs. Please try this settings:
```
"tidyHtml.optionsTidy": {
	"input-xml": true,
	"indent-spaces": 4,
	"wrap": 200
},
```

It is possible to use the setting `editor.tabsize`, great Idea. I will add this feature in the next release, but it needs time. My fun coding time is limited.

**Comment by BendingBender** [comment]
It is actually Angular 1 template HTML. Tried out the `input-xml` option, it seemed to not have any influence on the output.

The plugin formats my HTML correctly - I see the that my file is being changed, the only issue I have is that it indents with 2 spaces instead of 4. VS Code installed the plugin in version 1.5.0, could it be the root cause? How can I force it to use the newest version?

**Comment by AnWeber** [comment]
1.5 is the latest released version. VS Code does a good job. It is my fault, 1.6 got not released. I dumped my ubuntu dev vmware now I got no time to install Ubuntu and configure it right.

Please try this config:

```
{
	"markup": true,
	"output-xml": false,
	"input-xml": false,
	"show-warnings": true,
	"show-errors": 6,
	"numeric-entities": false,
	"quote-marks": false,
	"quote-nbsp": true,
	"quote-ampersand": false,
	"break-before-br": false,
	"preserve-entities": true,
	"uppercase-tags": false,
	"uppercase-attributes": false,
	"indent": "auto",
	"indent-with-tabs": false,
	"indent-spaces": 2,
	"indent-attributes": true,
	"sort-attributes": "alpha",
	"wrap": 250
}
```
It is the default config + index spaces 2.

**Comment by BendingBender** [comment]
Ok, it seems to ignore the options specified in workspace settings and only reads the options from user settings. I've just pasted my config into user settings and it worked fine.

**Comment by AnWeber** [comment]
that's strange. I am using it in the workspace settings. But user settings wins.

**Comment by BendingBender** [comment]
Shouldn't workspace settings win?

I've also tried to set something documented like `wrap` to 20, the plugin ignored it until I've added the config to user settings.

**Comment by AnWeber** [comment]
yep, you are right [workspace settings](https://code.visualstudio.com/docs/getstarted/settings) wins.
