### ISSUE TITLE
workspace.rootPath is deprecated

### ISSUE THREAD

**Issue by sglaser** [AnWeber/vscode-tidyhtml#13]
Trying to move my options from user settings to .htmlTidy

Once I noticed the capital T, I was trying to figure out what was considered the root path of the workspace. And was not able to find a configuration that worked.

Some google searching shows that the mechanism this extension uses to locate the rootPath (in GetSettings) is deprecated. I'm not sure when -- the Microsoft issues discussing this were from Oct 2017 so that build might be the default by now. 

I'm pretty new to vscode so I could easily have missed something.

Background: I'm trying to move configuration into files in my document git repos so other users will automatically get them. There will be many other folk editing in this repo most with almost no knowledge of vscode (or desire to learn it in detail).

**Comment by AnWeber** [comment]
Thanks for your issue. Using workspace.rootpath is deprecated, so I updated the extension to use the new workspaceFolders property (e9d66031d6b851a805dc2363cfb10f2b770a72e1).

**Comment by AnWeber** [comment]
There are two solutions for your use case of workspace settings. I prefer using the builtin VSCode workspace settings feature. Just copy your tidyhtml user settings to the workspace settings and commit the settings in your repo to use the same settings in your team. 

Using .htmlTidy file is a "deprecated" solution too support VSCode next to an Atom extension. But I changed completely too vscode. But you could still use this feature. Just add a .htmlTidy File in the workspace Root and you are fine. I attached an example.

[htmlTidy.txt](https://github.com/AnWeber/vscode-tidyhtml/files/1739829/htmlTidy.txt)

**Comment by sglaser** [comment]
Thanks for the quick response.

You should update the readme to indicate the new situation. Mention .htmlTidy is deprecated but remains for atom compatibility, workspace settings is likely better, and that you use the FIRST folder you find (in workspace order) that has an .htmlTidy file. 

I ended up using workspace settings as well. Glad to know I ended up at the preferred solution.

Thanks again. 

Steveg

**Comment by AnWeber** [comment]
I will update the readme with the next version. Thanks

**Comment by sglaser** [comment]
Just raised another minor issue and proposed a fix (pull request).

Please note that my pull request is UNTESTED.

Steve Glaser
sglaser@sglaser.com
