### ISSUE TITLE
Release 1.8.0 dropped execute permission from Darwin and Linux tidy executables

### ISSUE THREAD

**Issue by sglaser** [AnWeber/vscode-tidyhtml#15]
Things worked fine if I manually added executable permission (Darwin -- not tested on linux).

I just created a pull request that should fix this automagically at run time (check for execute permission and use chmod to add permission and try again). This change also adds information to error messages (like the location of the default tidy executable, which option to configure to set the tidy executable, ...)

**Comment by AnWeber** [comment]
pull request #14

**Comment by AnWeber** [comment]
Sorry, I published the extension from my windows machine. [On Windows vsce will lack POSIX file attributes](https://code.visualstudio.com/docs/extensions/publish-extension#_advanced-usage). Currently I download ubuntu and republish the extension in a vmware. 
I merged your pull request. Normally the chmod is not needed, if I publish it correctly, but it shouldn`t hurt to have a fallback. Thanks

**Comment by sglaser** [comment]
Thanks.
