### ISSUE TITLE
Angular 6 component html code was replaced with empty html shell

### ISSUE THREAD

**Issue by HopperTech** [AnWeber/vscode-tidyhtml#20]
Was working on an angular 6 app, specifically in a component I had created. Everything I modified the [component].component.html the content was replaced with either an empty html shell or wrapped some of the content in a shell, removing a portion. Never figured out the rhyme or reason of what was removed. 

finally uninstalled this plugin and everything is now working fine.

**Comment by AnWeber** [comment]
Tidy-HTML5 does only support "clean" html. Custom elements and Custom attributes are not supported. Maybe it get implemented in the future ([=> 5.7](https://github.com/htacg/tidy-html5/issues/677)). Recently I stopped using this extension myself, because it is not working like expected.
