### ISSUE TITLE
Since 1.7 HTML files are always marked as edited

### ISSUE THREAD

**Issue by kev23777** [AnWeber/vscode-tidyhtml#4]
- Modify the HTML file. (See the edited circle in the tab)
- Save the HTML
- tidyhtml formats the HTML and the file is saved
- The circle briefly turns back to an X before changing back to a circle without anything actually changing.
- Save again
- The circle briefly turns back to an X before changing back to a circle without anything actually changing.
- Repeat forever

**Comment by AnWeber** [comment]
hello,

thanks for your issue report. I get the same issue. The auto format happens in the event onDidSaveTextDocument. Since vscode 1.6 there is a onWillSaveTextDocument Event. Maybe the extension should use this event, to fix the issue. I will give it a try.

**Comment by AnWeber** [comment]
onWillSaveTextDocument fixes the edit state of the workbench editor. I published a new version of the extension. Please try the new version. Sorry for this annoying issue.

**Comment by kev23777** [comment]
Works great now, thanks.

A separate thing I noticed, and I'm not sure if it's VS Code or this plugin, is that if I make changes and save, then undo those changes and save, I can no longer redo those changes because the redo "clipboard" is now empty.

**Comment by AnWeber** [comment]
this is a tricky question. the extension does not actively change the clipboard. I only use official api calls. Therefore no, not my issue. But I couldn't reproduce the same issue in a js file.
