### ISSUE TITLE
How to format attribute without value

### ISSUE THREAD

**Issue by klauszhang** [AnWeber/vscode-tidyhtml#5]
very nice tool, thank you

just want to know how to **disable** this:

This code
```
<div layout-fill></div>
```

Will be formatted into 
```
<div layout-fill=""></div>
```

thank you

**Comment by AnWeber** [comment]
This extension is just a wrapper around the cli of Tidy-HTML 5. I did not
find a solution in the docs of the project (
http://api.html-tidy.org/tidy/quickref_5.2.0.html). I just accepted this
formatting style in my project. Maybe you ask your question in their repo:
https://github.com/htacg/tidy-html5/issues.

Thanks

Hao Zhang <notifications@github.com> schrieb am Do., 19. Jan. 2017 um
03:47 Uhr:

**Comment by AnWeber** [comment]
I found this issue in the repo of tidy html:
https://github.com/htacg/tidy-html5/issues/439.


Andreas Weber <weber.andreas@gmail.com> schrieb am Mi., 25. Jan. 2017 um
07:02 Uhr:

**Comment by klauszhang** [comment]
Thank you @AnWeber, the link is very useful. will close the issue.
