### ISSUE TITLE
Why does tidy format the '<' and '>' numeric operator?

### ISSUE THREAD

**Issue by elD1eg0** [AnWeber/vscode-tidyhtml#6]
When I use the operator "greater than" (>) or "less than" (<), it will replaced automatically by \&gt; and \&lt; 
How can I solve this?

**Comment by AnWeber** [comment]
Hello,

good question. I found no workaround in my angular project. I separated the
logic and the gui and only use named properties for binding. I would ask
the maintainer of the tidy project, but you already created a issue (
https://github.com/htacg/tidy-html5/issues/485). Thanks.

elD1eg0 <notifications@github.com> schrieb am Mi., 1. Feb. 2017 um
11:23 Uhr:
