### ISSUE TITLE
not working ??

### ISSUE THREAD

**Issue by Dandiccf** [AnWeber/vscode-tidyhtml#7]
I am running Visual Code for Mac v1.9 and have installed your plugin v1.3. 
But I could not find any way of making your plugin reformat my code. Nothing happens if I run the command, no log or error found...

thx for your help

**Comment by AnWeber** [comment]
Hello,

you could use the command "extension.tidyHtml". It triggers a manual format
of the document. If any error happens, a console.log with the error will be
written. Please open the developer tools and add the message to the issue.
I don't own a mac, sorry for the inconvenience.

Dandiccf <notifications@github.com> schrieb am Di., 7. Feb. 2017 um
11:24 Uhr:
