### ISSUE TITLE
Required input to end with "/> " error if ending with ">"

### ISSUE THREAD

**Issue by jcphlux** [AnWeber/vscode-tidyhtml#8]
Not a big deal when working from my repos because I always use closing tags. But this is not a required standard in html 5 so when working on repos that do belong to me there is not always proper closing tags on inputs.

**Comment by AnWeber** [comment]
just disable the option [input-xml](http://api.html-tidy.org/tidy/quickref_5.4.0.html#input-xml). In this case tidy-html uses the html parser and end tags can be omitted. But it also enable an extended validation for valid html attributes, which works not nicely with custom attributes (e.g. angularjs ng-click).

**Comment by jcphlux** [comment]
ok thanks 💯
