### ISSUE TITLE
Deletes contents of file

### ISSUE THREAD

**Issue by hallids** [AnWeber/vscode-tidyhtml#9]
I used the extension (press F1, type/select TidyHtml) on a file containing nothing but the HTML below, and it just deleted everything. I've tried on a couple of different files with same result.
```
<form>
<div>
<label for="username">Username</label>
<input type="text" id="username" required> </div>
<div>
<label for="password">Password</label>
<input type="password" id="password"> </div>
<button type="submit">Submit</button>
</form>
```

I am using Windows 10 Home, Visual Studio Code version 1.12.2

**Comment by AnWeber** [comment]
do you have the newest version of my extension? This version shows an error to close the input tag. With the default configuration for tidy html only valid xml is allowed. Please see issue #8

**Comment by hallids** [comment]
I have version 1.5.0, installed today via the vscode extensions sidebar.

Setting `input-xml` to false did not fix it.

**Comment by AnWeber** [comment]
On my machine it does not delete the content of the file. Do you have a
console message in the developer tools? Eventually another extension?

hallids <notifications@github.com> schrieb am Fr., 26. Mai 2017, 08:01:

**Comment by hallids** [comment]
There is nothing in the developer console.

Sorry, I don't understand the question in the last sentence.

**Comment by AnWeber** [comment]
I find no explanation, why the content of the file gets deleted. On my win10 machine I can not reproduce this behavior.

- Do you get this issue by triggering the format by using the tidyhtml command?

- What settings are configured? Try formatting this html without any settings changed.
```
<form><div><label for="username">Username</label><input type="text" id="username" required="true"/></div><div><label for="password">Password</label><input type="password" id="password"/> </div><button type="submit">Submit</button></form>
```

- Do you have any other extensions installed? Maybe one of them triggers this issue in coop with my extension.

Thanks for your patience.

**Comment by hallids** [comment]
So, I cleared my settings.json, keybindings.json and disabled all extensions except for this one, restarted my computer, and it still deletes the contents of the file.

This was with the html you provided, and using Ctrl+P, >TidyHtml.

In the developer tools console, it just says ```extensionHost.ts:285 [Extension Host] 10``` every time I run >TidyHtml (to be expected, I assume).

Actually, if I run it on an **empty file** it produces an error in the devtools console ([screenshot](https://pasteboard.co/cj6xi2ktE.png)). Not sure if that is useful or not.
```
shell.ts:474 Running the contributed command:'extension.tidyHtml' failed.
winjs.base.js:45 WARNING: Promise with no error callback:96
```

I'm not familiar with vscode extension development or debugging, but if there's anything else I can do, let me know.

**Comment by AnWeber** [comment]
hi,

I wanted to give an update for your issue report. I fixed the error on formatting an empty file. It was an invalid access to a null object.
I don't find the cause for your real issue. I also added tslint and strict typescript rules to highlight bad coding, but nothing hints to your description of the error. I added an extended traceLogging enabled by the new setting tracelogging. Maybe with this extended logging I may find your issue. But at the moment I can't publish a new update of my extension. I got some problems with my Personal access token, which I couldn't resolve till now. I will try it on another day. If you want to test it know, just checkout my repo. Type npm install on the command line and start the extension with F5 in vscode.

**Comment by Tackgnol** [comment]
It also removes DJANGO extensions 
```
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block%}

    <h1>Hello and welcome to the site!</h1>
    <h1>This is the index.html page</h1>

    {% endblock %}
```
it converts to
`    <h1>Hello and welcome to the site!</h1>
    <h1>This is the index.html page</h1>`

**Comment by AnWeber** [comment]
@Tackgnol your example tackles an other problem. tidy-html5 does not support template engines really well. Maybe this issue report is helpful:
https://github.com/htacg/tidy-html5/issues/505
